language: shell
os: linux

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: Bxh4dxOfZq9PWt+jEIsnDDWw4Tq8p+KLrGdZahHlzqWhBT4di+a279frMp/6eMVSwqjANQJNuaQHYEjGH/wO3Fi0eewcj3w5YrORU0DV+cAJin9lv0iwsc+05d4UX+Yxbt47k0ZYzLw78GdqUJ0355ZnpwizhLyjcAsFyZyZ1QFL2dIYhUwJuLW8A5UyeckydGSm1wXBobTBBqO93eln4DPOR4anuEs+UIf3LOp05QsKIk+QY/AZpeBTN/6HN99u8E0ynMK5GAujnlzWZnAFXd2S0ODyCp1jycyg8dpUeDlUEfCQeuAhIOAKgQoJq0l4JlGw1r6XJ39SXLPjcJJO2i6YuONtDabF5WSS+UqtNTmU9IGYU8TU2dTVVXD3pzPB+YQNIaFsg+NVfUV7e/ys/rqgOAmJAKcNntu6aPOaLNnzyrWhLRWcuqzVOAwjy7pbCFyOnUIAlTnjnOYqXwL55ZqHrvF4dArz0pDuWVfrOZNegEhwuofdvr6mRvbtka4p8yJTCQeTbTvS1xsSlq16cQ3H1Kk/Y1nlm1Y0bgTHywK+Kq1PO9OeeTXv05eSCfuTyUPoCFE6DZ08QORhVgC6avg4cg7I4Gje/kCD3p5C6J8OmFjX4z8gKR1hUZSTR+U8r4Oz+lDER0QYnllW0oCJ501q76iyZ/lEBzBXGvI49no=
    template:
      - "Repo %{repository_slug} *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>)"
      - "%{author}: _%{commit_message}_"
      - "Execution time: *%{duration}*"
      - "Message: *%{message}*"
    on_success: always

services:
  - docker
env:
  - OLS_VERSION=1.6.13 PHP_VERSION=lsphp74 FOLDER=template TAG=latest
  - OLS_VERSION=1.6.13 PHP_VERSION=lsphp74 FOLDER=template
  - OLS_VERSION=1.6.13 PHP_VERSION=lsphp73 FOLDER=template

script:
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        cd $FOLDER && bash build.sh --ols $OLS_VERSION --php $PHP_VERSION --tag "$TAG" --push
    else
        cd $FOLDER && bash build.sh --ols $OLS_VERSION --php $PHP_VERSION
    fi    